// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX63HEo0BpEUNFo0rbcysEjMKz_KrVFe0',
    appId: '1:715567994243:web:8afd65f1efbd093c8112b6',
    messagingSenderId: '715567994243',
    projectId: 'bookbuddy-4084a',
    authDomain: 'bookbuddy-4084a.firebaseapp.com',
    storageBucket: 'bookbuddy-4084a.firebasestorage.app',
    measurementId: 'G-HZ7T16W6VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuTj_p14c_9ted0yauVenHVMgv9GTr-tM',
    appId: '1:715567994243:android:e1a568ed7a8fb1668112b6',
    messagingSenderId: '715567994243',
    projectId: 'bookbuddy-4084a',
    storageBucket: 'bookbuddy-4084a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDr5nWS7skOIPSOmyIZ9oVwCGOVHI1gUg',
    appId: '1:715567994243:ios:3da5cd1369ab65408112b6',
    messagingSenderId: '715567994243',
    projectId: 'bookbuddy-4084a',
    storageBucket: 'bookbuddy-4084a.firebasestorage.app',
    iosBundleId: 'com.example.bookBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDr5nWS7skOIPSOmyIZ9oVwCGOVHI1gUg',
    appId: '1:715567994243:ios:3da5cd1369ab65408112b6',
    messagingSenderId: '715567994243',
    projectId: 'bookbuddy-4084a',
    storageBucket: 'bookbuddy-4084a.firebasestorage.app',
    iosBundleId: 'com.example.bookBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX63HEo0BpEUNFo0rbcysEjMKz_KrVFe0',
    appId: '1:715567994243:web:c1ca69817c2514578112b6',
    messagingSenderId: '715567994243',
    projectId: 'bookbuddy-4084a',
    authDomain: 'bookbuddy-4084a.firebaseapp.com',
    storageBucket: 'bookbuddy-4084a.firebasestorage.app',
    measurementId: 'G-K579J9L148',
  );
}
